### ISSUE TITLE
Can not get linux loaded

### ISSUE THREAD

**Issue by hedleyd** [Efinix-Inc/br2-efinix#1]
Firstly thanks for this wonderful project - I have followed the instructions for the t120f324 board , copied the sdcard.img to a 32gb sdcard and get the following - 1. when the sd caard is plugged in nothing happens - when I remove the sd card I get the output shown in the attachment . 

Question 2 is - are the plans to , or how could I include ethernet functionality which is essential for our envisaged edge device which would be on a POE+ network 
![linux on efinix stop](https://user-images.githubusercontent.com/7720490/206861113-38775f07-c273-41f7-97a4-0694da0f2a62.JPG)

**Comment by cagrimkahraman** [comment]
# Flash Linux Image onto SD Card

1. Check the existing disk on the computer.
   
   ```bash
   sudo fdisk -l
   ```

2. Insert the SD card into the computer and run this command again to see the detected SD card. Note down the device name. For example `/dev/sdx`. If in doubt, remove the SD card and run the command again.
   
   ```bash
   sudo fdisk -l
   ```

3. Copy the `sdcard.img` to the SD card.
   
   > Warning: There is a significant risk of damage to your filesystem if you use the wrong /dev/sdx. Make sure you get it right!
   
   ```bash
   sudo dd if=sdcard.img of=/dev/sdx status=progress
   ```

4. Unmount the SD card
   
   ```bash
   sudo umount /dev/sdx
   ```

**Comment by efxmnalim** [comment]
Could you type `mmcinfo` at U-boot command prompt. If you see SD card info means that the SD card not flash properly with Linux image.

**Comment by hedleyd** [comment]
Thanks for suggestions - I put the TI120F324 aside and tried on the T160F225 dev kit that allowed me to get further . I typed in the suggested mmcinfo and got response shown in the first attachment . It then contuniues with the boot and stops at the line Run /sbin/init as init process
![ti60mmcinfo](https://user-images.githubusercontent.com/7720490/206981854-b2f57a6e-4201-4f46-b247-11113da508ec.JPG)
![run to sbininit](https://user-images.githubusercontent.com/7720490/206981877-3ebca4d9-dd8b-4739-a632-a51f7ace4f62.JPG)
![run to sbininit](https://user-images.githubusercontent.com/7720490/206981975-628d529b-477d-4150-a4c7-532b65494fab.JPG)

**Comment by hedleyd** [comment]
My setup is - Ti60F225 , USB-C cable connected to host - have tried Sandisk and Sandisk Entreme 32GB cards onto which the sdcard.img is written using balena Etcher. On both dev kits I can not get a reliable boot - has anyone got this working . I have attached the steps I followed. 
[efinix linux setup.xlsx](https://github.com/Efinix-Inc/br2-efinix/files/10217649/efinix.linux.setup.xlsx)

**Comment by efxmnalim** [comment]
Could you check the J3 jumper on T120F324 and connect it to 3.3V.

**Comment by hedleyd** [comment]
I did that and moved the jumper - no change but noticed that when the sd
card is inserted,  D7 led goes off and when ejected D7 goes on again - I am
using the prebuilt soc.hex and have tried both 1 and 4 cores . I tried
building the soc from scratch as per instructions , but do get a lot of
warnings regarding timing even though as per instructions I did set timing
to 3 - so back to the drawing board

Hedley Davidson
Managing Director
Cynaps Technologies Pty Ltd
***@***.***
078-458-7476 ( Mobile )

**Comment by hedleyd** [comment]
There appears to be a lot more in the soc that is covered in the docs - All i'm trying to establish is if anyone has got linux to boot and work reliably on either the T120 or Ti60 based dev kits ? - If so we will try and figure out how to get it to work and then update the docs - I have attached what I/O seems to be in the sample soc vs the few GPIO that the docs suggest are needed which are highlighted with red line . 
![soc for linux](https://user-images.githubusercontent.com/7720490/207602873-8fda3129-1ebf-4b6d-9a41-0831cfc0d4b3.PNG)

**Comment by efxmnalim** [comment]
Could you check the PMOD micro sd is connected to J12 port on T120F324 devkit. Led D7 should not turn off when the card is inserted. Also make sure  J3 jumper connected to 3.3v.

**Comment by hedleyd** [comment]
I am very embarrassed to let you know that I had connected the PMOD **to the wrong port** - Thanks again for your input . I managed to get linux to boot . then did cat /proc/info and the response is Processor:0 hart:0 isa rv32imafd

**Comment by efxmnalim** [comment]
Great! I will update the docs for the J3 jumper connection to 3.3v on T120F324 devkit.

**Comment by hedleyd** [comment]
I rebuilt gpio as suggested and all worked perfectly - MANY thanks for prompt reply

**Comment by efxmnalim** [comment]
> Great! I will update the docs for the J3 jumper connection to 3.3v on T120F324 devkit.

https://github.com/Efinix-Inc/br2-efinix/commit/472fceeb53e3077aa08aa71e75c594523f5512bb
