### ISSUE TITLE
Query on how to setup ethernet in Linux using Ti180 board 

### ISSUE THREAD

**Issue by rohaya2021** [Efinix-Inc/br2-efinix#11]
Hi, 

Is the ethernet for Linux ready? If yes, can you provide me information on how to do the setup on Ti180 board. Thanks

**Comment by hedleyd** [comment]
I too , am eagerly waiting for its release as it is key for our product
development . I am hoping for an ' early beta release ' by june and check
out the site every morning to see if new code has been uploaded.


Hedley Davidson

**Comment by efxmnalim** [comment]
duplicate query. See https://github.com/Efinix-Inc/br2-efinix/issues/6.
