### ISSUE TITLE
Missing python dependency, jinja2

### ISSUE THREAD

**Issue by joo-jie** [Efinix-Inc/br2-efinix#13]
Reference Issue to dt-generator: https://github.com/Efinix-Inc/sapphire-soc-dt-generator/issues/7

**Comment by efxmnalim** [comment]
README.md: fix step to install jinja2 python package https://github.com/Efinix-Inc/br2-efinix/commit/c6add2452c9e7ffa59e4d3873b5dbe691a61a2de
