### ISSUE TITLE
gst-plugin-scan[135]: unhandled signal 11 code 0x1 at 0x00000004 in libglib-2.0.so

### ISSUE THREAD

**Issue by cagrimkahraman** [Efinix-Inc/br2-efinix#2]
![image](https://user-images.githubusercontent.com/49093286/207319301-e22f6295-23a5-4457-b22e-b2357c3152c6.png)

![image](https://user-images.githubusercontent.com/49093286/207319442-3cd6c540-4c7e-4f3b-9ae5-77bc0ef14dc4.png)

Hi,

I want to add the gstreamer on my linux dirstory. I added gstreamer from target devices page of buildroot but its not working. I got this error and couldn't find a solution. I updated the buildroot (2022.11 )to the latest version but that didn't work out the solution I did.

![image](https://user-images.githubusercontent.com/49093286/207320720-45510509-3fa3-4788-bb60-71d8ce49f0cb.png)

**Comment by efxmnalim** [comment]
What is buildroot configuration you put in `configs/efinix_t120f324_defconfig` ?

I try to reproduce you issue using current release of br2-efinix 2021.05.5 as follows
1. clone this repo
2. add `BR2_PACKAGE_GSTREAMER1=y` in `configs/efinix_t120f324_defconfig`
3. build the image

This is my result
![image](https://user-images.githubusercontent.com/95894476/207559199-5bb68b31-540a-432c-b281-705be60357fd.png)

**Comment by efxmnalim** [comment]
I able to reproduce the issue. Seem like the `libglib2` crash when compile with floating-point instruction extension RV32IMAFD. `gst-inspect-1.0` works fine without floating-point RV32IMA instruction set.

**Comment by cagrimkahraman** [comment]
![image](https://user-images.githubusercontent.com/49093286/207820138-889e5af1-b7cd-4d1f-aa61-85085f57e4d2.png)
![image](https://user-images.githubusercontent.com/49093286/207820256-441bdaa2-b6cc-4a0d-a411-798f509f26ad.png)
![image](https://user-images.githubusercontent.com/49093286/207820319-6e03ba29-429a-41f1-9811-3ec2216be5f7.png)
![image](https://user-images.githubusercontent.com/49093286/207820407-9b002b6a-711d-4c15-a4c5-d7b15051f132.png)
![image](https://user-images.githubusercontent.com/49093286/207820531-8022ef7a-dd20-4bd5-ae92-12fab4d345f6.png)

I changed instruction setting for RV32IMA but the errors is still same. How do i change the setting.

**Comment by efxmnalim** [comment]
Try to enable these configurations in `br2-efinix/boards/efinix/t120f324/linux/linux.config`. Also test it with floating-point enable. I think this issue has nothing to do with floating-point instruction.

```
CONFIG_NET=y
CONFIG_UNIX=y
```

**Comment by cagrimkahraman** [comment]
![image](https://user-images.githubusercontent.com/49093286/208040034-d416dce3-1e69-4814-ac97-9bbbf185d09d.png)


Thank you. it is working now. As far as I understand you are working on ethernet. How do i integrated the ethernet in my distro. I have to have linux driver of efinix tri-mode ethernet ip but i couldnt find on this repo.
