### ISSUE TITLE
No Linux is loaded after running command minicom -D /dev/ttyUSB2 in Centos 7.9

### ISSUE THREAD

**Issue by rohaya2021** [Efinix-Inc/br2-efinix#3]
![minicom_command](https://user-images.githubusercontent.com/90079835/209293645-5f608006-6f4d-4a10-ad0c-c589ee9226d9.jpg)

I have followed the instruction to load Linux on ti60f225 but failed. Here is the flow which I used:
1) Generate soc.h using Efinix Sapphire RISC-V SoC  flow (efinity version 2022.2). 
 2) source init.sh in br2-efinix
 3) run makefile
 4) Combine multiple images files ( soc.hex, fw_jump.bin  and u-boot.bin) and program the SPI flash
 5) use dd command to flash linux image sdcard.img to a 16g sdcard. 
 6) run minicom -D /dev/ttyUSB2

**Comment by hedleyd** [comment]
sudo minicom  -D /dev/ttyUSB0   -- worked for me
as a sanity check try connecting with teraterm from windows environment ,
or putty - Baud 115,200


Hedley Davidson
Managing Director
Cynaps Technologies Pty Ltd
***@***.***
078-458-7476 ( Mobile )

**Comment by rohaya2021** [comment]
Hi Hedley,
I figure out I missed the modify bootloader part. I follow https://github.com/Efinix-Inc/br2-efinix/blob/main/docs/modify_fpga_bootloader.md but couldn’t find file riscv-xpack-toolchain_8.3.0-2.3_linux
I didn’t install RISCV SDK because the link said End of Life. I installed efinity-riscv-ide-2022.2.3 instead but couldn’t find riscv-xpack-toolchain_8.3.0-2.3_linux
Maybe I need to launch the software and run IP manager from there. 
Anyway, what is the command to launch efinity-riscv-ide-2022.2.3?
Do I create custom SoC Sapphire configuration from efinity-riscv-ide-2022.2.3 or efinity software?
Thanks

**Comment by efxmnalim** [comment]
Please `git pull` again to get the latest changes from this repo. The efinity-riscv-ide-2022.2.3 already come with RISCV toolchain. The `modify_bootloader.sh` script will handle the compilation of bootloader.

**Comment by rohaya2021** [comment]
I already installed the latest br2-efinix 2021.05.5
i want to run modify_bootloader.sh in br2-efinix/boards/efinix/common but I don't have riscv-xpack-toolchain_8.3.0-2.3_linux
Where to get the folder?

**Comment by efxmnalim** [comment]
no need to give the path of riscv-xpack-toolchain anymore. It replaced with path to efinity-riscv-ide-2022.2.3. For example `/home/user/efinity/efinity-riscv-ide-2022.2.3`

**Comment by rohaya2021** [comment]
I have successfully run modify_bootloader.sh 
Do I have to run compile bootloader program?

**Comment by efxmnalim** [comment]
`modify_bootloader.sh` script already compile the bootloader program. Just recompile the Efinity project

**Comment by rohaya2021** [comment]
How to recompile the Efinity project?

**Comment by efxmnalim** [comment]
Open the Efinity software then load your generated sapphire soc project. After that click the screw button to compile the project.

**Comment by rohaya2021** [comment]
I followed the flow until command to run minicom to boot the Linux but failed. How to check what went wrong?

**Comment by hedleyd** [comment]
I will document all the steps I followed on an excel spreadsheet

With a bit of help from the creator everything worked fine so the process
from board out of the box to booting went well.

I made a few silly mistakes which I will include in the doc and post within
the next day or two .

Hedley Davidson

***@***.***

**Comment by rohaya2021** [comment]
I attach here my flow in Word. I tried minicom -D  /dev/ttyUSB0 but failed. 
[buildroot_flow_Rev2.docx](https://github.com/Efinix-Inc/br2-efinix/files/10312538/buildroot_flow_Rev2.docx)
Next plan is to try on Putty at Windows.

**Comment by rohaya2021** [comment]
![Error_Message_After_Linux_is_loaded](https://user-images.githubusercontent.com/90079835/209769921-b6f09b66-fdaa-4cff-84eb-14d292f01c9a.jpg)
I can get the Linux loaded by pressing Reset button on Ti60F225 board but got error message as shown on attached jpg file.

**Comment by efxmnalim** [comment]
Could you type `mmcinfo` at U-boot command prompt

**Comment by rohaya2021** [comment]
I can't write anything on the U-boot prompt. I have to exit minicom once it got stucked trying to get the kernel image from sdcard.

**Comment by efxmnalim** [comment]
Any reason to use these pins assignment for the SPI1?
```
system_spi_1_io_data_0      Pin=M2 Resource=GPIOL_N_02
system_spi_1_io_data_1      Pin=H4 Resource=GPIOL_N_04
system_spi_1_io_sclk_write  Pin=N2 Resource=GPIOL_P_02
system_spi_1_io_ss          Pin=P2 Resource=GPIOL_P_00
```

Could you try to use [this](https://github.com/Efinix-Inc/br2-efinix/blob/main/docs/generate_sapphire_soc_for_linux.md#assign-pinout-for-spi-1) pin assignment for Ti60F225?

**Comment by rohaya2021** [comment]
I got mismatch voltage in I/O standard assignment in bank and instance for all the above pins if I follow the suppose assigned resources.

**Comment by efxmnalim** [comment]
Use [this ](https://github.com/Efinix-Inc/br2-efinix/blob/main/docs/generate_sapphire_soc_for_linux.md#assign-pinout-for-spi-1)pin assignment. Just change the I/O bank voltage to `3.3V` for `TR bank` in the `Efinity Interface Designer -> Device Settings -> IO Banks`. Also change the `J5` jumper setting on the Ti60F225 to `pin 1 and 2`.

**Comment by rohaya2021** [comment]
Am I using the correct soc.xml? I open soc.xml from /project/soc/ip/soc1/Ti60F225_devkit folder. There is another soc.xml from folder /project/soc. The later was created when I generate the custom SoC.

**Comment by rohaya2021** [comment]
I rerun using configuration pinout for SPI 1. Here is the message I received after running minicom. 

![couldnot_initialize_timer](https://user-images.githubusercontent.com/90079835/210025921-9a154ba0-407f-440f-b630-5817dfc41551.jpg)

**Comment by rohaya2021** [comment]
![linux_loaded](https://user-images.githubusercontent.com/90079835/210052300-504694ff-caf7-4a34-8b29-179463c726c0.jpg)
I am able to load linux. Thanks for the flow Hedley. I used soc.h and soc.hex from br2_efinix directory and it worked.

**Comment by rohaya2021** [comment]
I tried to reboot linux today but it complained couldn't get the kernel image. I am using the same sdcard last week. Do I need to rerun the whole flow?

**Comment by efxmnalim** [comment]
It can be the SD card not detected. Try run `mmcinfo` on U-boot terminal or flash the Linux image again.

**Comment by rohaya2021** [comment]
![Cant_Read_Image_Jan4](https://user-images.githubusercontent.com/90079835/210474665-7801ad3e-3463-4f1a-9e2e-4f6d055d8fda.jpg)
I flash the Linux image again but still it can't get the kernel image.

**Comment by rohaya2021** [comment]
Please close this issue because I no longer loading Linux on Centos 7.9. I reinstalled my workstation with Ubuntu 18.04
