### ISSUE TITLE
Using Ubuntu 18.04 to run efinity

### ISSUE THREAD

**Issue by rohaya2021** [Efinix-Inc/br2-efinix#4]
I got this message when running efinity in Ubuntu 18.04
cannot execute binary file: Exec format error

**Comment by efxmnalim** [comment]
Which Efinity version you use? Have you check the file permission?

**Comment by rohaya2021** [comment]
The problem had been solved previously. These are the versions info:
buildroot 2021.05.3
u-boot 2021.04
opensbi 0.9
Linux kernel 5.10
gcc 8.4 

Now I can load Linux but it got stuck while booting for almost 24h. 
![image](https://user-images.githubusercontent.com/90079835/213342885-44c5f963-56ee-435f-b0e4-aed7cad6fccf.png)

**Comment by efxmnalim** [comment]
The software version stated are not Efinity software. Please open another ticket for new issue.

**Comment by rohaya2021** [comment]
I already opened a new ticket (issue 5)
