### ISSUE TITLE
Hang while loading Linux on Ubuntu version 18.04 and efinity 2022.2

### ISSUE THREAD

**Issue by rohaya2021** [Efinix-Inc/br2-efinix#5]
![image](https://user-images.githubusercontent.com/90079835/213345760-61a3427c-472b-4748-b7aa-6809c4d027b2.png)

I tried to boot Linux on Ti60F225 but it hangs. I am using efinity version 2022.2

**Comment by rohaya2021** [comment]
I am using the latest bitstream (2021.05.6)

**Comment by efxmnalim** [comment]
Hang at which part? 
Also check the jumper setting for Ti60F225.
https://github.com/Efinix-Inc/br2-efinix/blob/main/docs/setup_development_board.md#setup-ti60f225

Try use snipping tool in Windows or [Ubuntu Screenshot](https://linuxconfig.org/how-to-take-a-screenshot-on-ubuntu-18-04-bionic-beaver-linux) to take the screenshot

**Comment by rohaya2021** [comment]
![Screenshot from 2023-01-19 15-47-34](https://user-images.githubusercontent.com/90079835/213385160-56898f75-fd83-45ca-bab9-e8b650862c21.png)
It got stucked as shown on attached picture. 
Setup Ti60F225 are correct and confirmed with multimeter.

**Comment by efxmnalim** [comment]
Try to press CRESET at SW2 a few times and see if it still stuck at same output prompt.

**Comment by rohaya2021** [comment]
SW2 or SW3? I press SW2 a few times still got message can't get kernel image.

**Comment by rohaya2021** [comment]
It still doesn't work. I also try pressing SW3 many times.  The final message was it can't get the kernel image.

**Comment by efxmnalim** [comment]
Seem like it's not detecting the sd card. Check the connection of the sd card?
What is the board version? Ti60F225 Rev A?

**Comment by rohaya2021** [comment]
![Ti60F225](https://user-images.githubusercontent.com/90079835/215714236-f194cfba-e347-4bd1-870f-3ffb5ffa2d61.jpg)
I am not sure what Rev of the board.

**Comment by efxmnalim** [comment]
It should be on the devkit. Next to USB type C port

**Comment by rohaya2021** [comment]
![Ti60F225_RevA2](https://user-images.githubusercontent.com/90079835/215721848-5bd17119-8420-497d-aafc-06e9be9b190b.jpg)
RevA2

**Comment by rohaya2021** [comment]
I changed my SD card to a new one. Still it can't read the kernel image.

**Comment by efxmnalim** [comment]
Try recompile the Efinity project from this repo for Ti60F225 and program the board again.

**Comment by rohaya2021** [comment]
I forgot to exit minicom properly. Now /dev/ttyUSB2 is not recognized. Can you advise how to retrieve /dev/ttyUSB2 so that I can rerun minicom again? Thanks

**Comment by rohaya2021** [comment]
Please ignore my previous question.

**Comment by rohaya2021** [comment]
I am able to load Linux after changing to a new Ti60F225 board. May I know what is the best way to shutdown? Is it poweroff or can you suggest another command?

**Comment by rohaya2021** [comment]
Or can I leave minicom by typing exit command?

**Comment by efxmnalim** [comment]
Currently shutdown and reboot command are not supported. You can give shutdown command but the board will not power off.

**Comment by rohaya2021** [comment]
May I know what is the best way to exit from minicom? Can I just leave with command ctrl + a + x or need to properly shut down by typing command poweroff first?

**Comment by efxmnalim** [comment]
You can type shutdown first then exit the minicom with ctrl+a+x. But, the board will not power off. So you need to turn off the switch on the board.
