### ISSUE TITLE
Ethernet functionality 

### ISSUE THREAD

**Issue by hedleyd** [Efinix-Inc/br2-efinix#6]
Not an issue , but a request to please update me when Ethernet capability will be included in the Linux buildroot for the dev boards . This will be a game changer for ai edge device development  as connectivity will be there,  plus Linux to run the code , plus the fpga fabric for edge device sensor handling . hedley@cynaps.co.za

**Comment by efxmnalim** [comment]
The ethernet example design are available for supported boards. See 
**Ti60F225**

- [boards/efinix/ti60f225/hardware/ethernet](https://github.com/Efinix-Inc/br2-efinix/blob/main/boards/efinix/ti60f225/hardware/ethernet)

**Ti180J484**

- [boards/efinix/ti180j484/hardware/ethernet](https://github.com/Efinix-Inc/br2-efinix/blob/main/boards/efinix/ti180j484/hardware/ethernet)


**Ti375C529**

- [boards/efinix/ti375c529/hardware/soc](https://github.com/Efinix-Inc/br2-efinix/blob/main/boards/efinix/ti375c529/hardware/soc)
- [boards/efinix/ti375c529/hardware/unified_hw](https://github.com/Efinix-Inc/br2-efinix/blob/main/boards/efinix/ti375c529/hardware/unified_hw)
