### ISSUE TITLE
Is Python already installed in buildroot Linux? If not, how do I run opencv? 

### ISSUE THREAD

**Issue by rohaya2021** [Efinix-Inc/br2-efinix#7]

**Comment by efxmnalim** [comment]
Are you asking Python package support or OpenCV with Python package support?

Python package already supported by Buildroot. See [here](https://github.com/buildroot/buildroot/blob/2021.05.3/package/python3/Config.in#L5).
OpenCV with Python package also supported. See [here](https://github.com/buildroot/buildroot/blob/2021.05.3/package/opencv3/Config.in#L155).
It require python-numpy but not support for RISCV. See [here](https://github.com/buildroot/buildroot/blob/2021.05.3/package/python-numpy/Config.in#L1)

You just need to add it in the buildroot defconfig file.
For example to add python3 package in the buildroot defconfig for Ti60F225 board.

1. Add `BR2_PACKAGE_PYTHON3=y` to `configs/efinix_ti60f225_defconfig`
2. Run `init.sh` script with `-r` option
```
. init.sh ti60f225 /path/to/soc.h -r
```

**Comment by rohaya2021** [comment]
I followed your steps and able to load linux with Python3. May I know how to check whether Python3 already added in the buildroot Linux? I type python3 -v, nothing appears.

**Comment by rohaya2021** [comment]
Please ignore my query. I type which python3 and /usr/bin/python3 appears. Tqvm, I will close this ticket.
